/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Aurelian Finance — tonal spot palette (light)
        background: '#f9f9fe',
        surface: {
          DEFAULT: '#f9f9fe',
          dim: '#d7dae4',
          bright: '#f9f9fe',
          lowest: '#ffffff',
          low: '#f2f3fb',
          container: '#ecedf6',
          high: '#e6e8f1',
          highest: '#dfe2ed',
          variant: '#dfe2ed',
        },
        content: {
          DEFAULT: '#2f323b',
          variant: '#5b5f68',
          inverse: '#9c9ca2',
        },
        outline: {
          DEFAULT: '#777b84',
          variant: '#aeb2bc',
        },
        primary: {
          DEFAULT: '#4c5e8b',
          dim: '#40527f',
          on: '#f9f8ff',
          container: '#b6c8fc',
          'on-container': '#2e416c',
          fixed: '#b9cbff',
          'fixed-dim': '#a8bbee',
          'on-fixed': '#192d57',
          'on-fixed-variant': '#384a76',
        },
        secondary: {
          DEFAULT: '#585f72',
          dim: '#4c5366',
          on: '#f9f8ff',
          container: '#dbe2f9',
          'on-container': '#4a5164',
          fixed: '#dbe2f9',
          'fixed-dim': '#cdd4eb',
          'on-fixed': '#383f51',
          'on-fixed-variant': '#545b6e',
        },
        tertiary: {
          DEFAULT: '#6b5680',
          dim: '#5f4b73',
          on: '#fff6ff',
          container: '#e7cdfe',
          'on-container': '#56426a',
          fixed: '#e7cdfe',
          'fixed-dim': '#d9bfef',
          'on-fixed': '#433056',
          'on-fixed-variant': '#604c74',
        },
        danger: {
          DEFAULT: '#a83836',
          dim: '#67040d',
          on: '#fff7f6',
          container: '#fa746f',
          'on-container': '#6e0a12',
        },
        positive: '#2e7d5b',
      },
      fontFamily: {
        display: ['Manrope', 'system-ui', 'sans-serif'],
        sans: ['"Hanken Grotesk"', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px' }],
        'body-md': ['16px', { lineHeight: '24px' }],
        'body-sm': ['14px', { lineHeight: '20px' }],
        'data-mono': ['14px', { lineHeight: '20px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      boxShadow: {
        'level-1': '0px 4px 20px rgba(76, 94, 139, 0.06)',
        'level-2': '0px 12px 32px rgba(76, 94, 139, 0.12)',
        soft: '0px 4px 20px rgba(15, 23, 42, 0.05)',
      },
      spacing: {
        gutter: '24px',
        'container-padding': '32px',
      },
      maxWidth: {
        content: '1440px',
      },
    },
  },
  plugins: [],
}
